spring:
  datasource:
   username: root
   password: Zxcv!234
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/user_dev1?characterEncoding=UTF-8&useSSL=false
logging:
  level:
    com.baomidou: debug
flyway:
  enabled: true
  locations: classpath:/db
#  创建记录表，强制数据迁移
  baseline-on-migrate: true