spring:
  datasource:
   username: sa
   password: password
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   schema: classpath:db/schema.sql
   data: classpath:db/data.sql
#   url: jdbc:h2:file:./db/V1_0__init
  h2:
    console:
      path: /h2
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    com.baomidou: debug
#flyway:
#  enabled: true
#  locations: classpath:/db
##  创建记录表，强制数据迁移
#  baseline-on-migrate: true